/**
 * Per-container colors (cor-CORE.CORRELATE-000007), ported from cttc's
 * `src/shared/format/colors.ts`: each series key gets a slot the first time
 * it is seen and keeps it, so a container's color never shuffles as
 * containers come and go or records refresh. Slots 0-7 are the curated
 * `--series-1..8` tokens (cor-CORE.UI-000001); later slots are generated by
 * golden-angle hue rotation.
 */

export type SlotMap = Readonly<Record<string, number>>;

/** The curated palette tokens (tokens.css), in slot order. Listed
 * explicitly so the token-coverage test can check each one exists. */
export const CURATED_TOKENS = [
  "--series-1",
  "--series-2",
  "--series-3",
  "--series-4",
  "--series-5",
  "--series-6",
  "--series-7",
  "--series-8",
] as const;

export const CURATED_SLOTS = CURATED_TOKENS.length;

/** Adds slots for any new keys -- in sorted order, after every existing slot
 * -- and returns the same map when nothing is new. */
export function assignSlots(existing: SlotMap, keys: readonly string[]): SlotMap {
  const fresh = [...new Set(keys)].filter((k) => !(k in existing)).sort();
  if (fresh.length === 0) return existing;
  let next = Object.values(existing).reduce((max, slot) => Math.max(max, slot), -1) + 1;
  const out: Record<string, number> = { ...existing };
  for (const key of fresh) out[key] = next++;
  return out;
}

/** The color for a slot: a token reference for the curated slots, else a
 * generated HSL (darker text-safe lightness for light themes). */
export function colorForSlot(slot: number, dark: boolean): string {
  if (slot < CURATED_SLOTS) return `var(${CURATED_TOKENS[slot]})`;
  const hue = (slot * 137.508) % 360;
  return `hsl(${hue.toFixed(1)}, 68%, ${dark ? 62 : 42}%)`;
}

/** Resolves a CSS-variable color to its computed value for canvas drawing,
 * which doesn't understand CSS variables; other colors pass through. */
export function resolveColor(color: string, readVar: (name: string) => string): string {
  const match = /^var\((--[a-z0-9-]+)\)$/.exec(color);
  if (!match) return color;
  return readVar(match[1]).trim() || color;
}
